{
 "title": "mle_service_dashboard",
 "description": "mle-project-sprint-3",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Квантили предсказаний",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.05, ml_service_predictions_bucket)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.5, ml_service_predictions_bucket)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, ml_service_predictions_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Кол-во запросов в секунду",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count{handler='/predict', instance=\"ml_service:1702\", job=\"scrapping-main-app\", method=\"POST\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Изменение кол-ва запросов с неправильными параметрами",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(ml_service_err_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Потребление RAM",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}